// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://weoyaethincvhpwxbzbp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indlb3lhZXRoaW5jdmhwd3hiemJwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzMDY0NzksImV4cCI6MjA2Nzg4MjQ3OX0.sgG_J5zNWQwXP-BM67DdvbSa7y368SWI6uGEx93UYDU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});